// ============================================================
// pixelIcons — tiny hand-drawn pixel icons, painted from string
// grids so they stay crisp at any integer scale.
//
//   partIcon(id)  – one icon per rig part: 24-wide HI_GRIDS drawn at 2x
//                   (frames, legs and plating use the mech sprites)
//   uiIcon(name)  – currency / stat / reward icons for the DOM
//   iconCanvas()  – the same pixels as a canvas, for the battle view
//
// Grid letters: k ink outline, w white, y yellow, o orange, r red,
// R pink-red, p purple, q plum, c cyan, s sky, n navy, g lime,
// e green, l silver, d slate, t steel. Part grids also use
// a (part colour), h (its highlight) and b (its shadow).
// ============================================================

import { getPart, rarityColor } from '../meta/Mech.js';
import { torsoCanvas, legsCanvas, clearMechSpriteCache } from './mechSprite.js';

const PAL = {
  k: '#1a1c2c', w: '#f4f4f4', y: '#ffcd75', o: '#ef7d57', r: '#b13e53', R: '#ff5d73',
  p: '#c46fd6', q: '#5d275d', c: '#73eff7', s: '#41a6f6', n: '#29366f', g: '#a7f070',
  e: '#38b764', l: '#94b0c2', d: '#566c86', t: '#333c57',
};

function shade(hex, amt) {
  const n = parseInt(hex.slice(1), 16);
  const f = (s) => {
    const v = (n >> s) & 255;
    return Math.max(0, Math.min(255, Math.round(amt > 0 ? v + (255 - v) * amt : v * (1 + amt))));
  };
  return `rgb(${f(16)}, ${f(8)}, ${f(0)})`;
}

// ---------- Fallback part grids (12 wide), one shape per type ----------

const TYPE_GRIDS = {
  frame: [
    '....kkkk....',
    '...khhhhk...',
    'kkkkaaaakkkk',
    'khhkawwakhhk',
    'kbbkaaaakbbk',
    'kkkkbbbbkkkk',
    '...kbkkbk...',
    '..kbbk.kbbk.',
    '..kkkk.kkkk.',
  ],
  legs: [
    '...kkkkkk...',
    '..khhhhhhk..',
    '..kaaaaaak..',
    '..kbkkkkbk..',
    '.khk....khk.',
    '.kak....kak.',
    'khak....kahk',
    'kbk......kbk',
    'kbbk....kbbk',
    'kkkkk..kkkkk',
  ],
  armor: [
    '.kkkkkkkkkk.',
    'khhhhhhhhhhk',
    'khaaaaaaaabk',
    'khaaawwaaabk',
    'khaaawwaaabk',
    '.kaaaaaaabk.',
    '.kbaaaaaabk.',
    '..kbaaaabk..',
    '...kbbbbk...',
    '....kkkk....',
  ],
  drone: [
    'kkk......kkk',
    'khhk....khhk',
    '.kkkkkkkkkk.',
    '..kaaaaaak..',
    '..kawwwwak..',
    '..kaaaaaak..',
    '..kbbbbbbk..',
    '...kkkkkk...',
    '....k..k....',
  ],
  module: [
    '..k.k.k.k...',
    '.kkkkkkkkk..',
    'kkhhhhhhhbkk',
    '.khaaaaaabk.',
    'kkhawwwwabkk',
    '.khaaaaaabk.',
    'kkhbbbbbbbkk',
    '.kkkkkkkkk..',
    '..k.k.k.k...',
  ],
};

// ---------- UI grids (8-10 wide) ----------

const UI_GRIDS = {
  gold: ['..kkkk..', '.kyyyyk.', 'kyywyyok', 'kywyyyok', 'kyyyyyok', 'kyyyyook', '.kooook.', '..kkkk..'],
  hp: ['.kk..kk.', 'kRRkkRRk', 'kRwRRRRk', 'kRRRRRRk', '.kRRRrk.', '..kRrk..', '...kk...'],
  key: ['.kkk......', 'kyyyk.....', 'kywykkkkkk', 'kyyyyyyyyk', 'kyyykkykyk', '.kkk..k.k.'],
  scrap: ['..k..k..', '.kkkkkk.', 'kklllldk', '.klkkdk.', '.klkkdk.', 'kkldddkk', '.kkkkkk.', '..k..k..'],
  skull: ['.kkkkkk.', 'kwwwwwwk', 'kwkwwkwk', 'kwkwwkwk', 'kwwwwwwk', '.kwkkwk.', '.kwwwwk.', '..kkkk..'],
  dmg: ['......kk', '.....kwk', '....kwk.', '.k.kwk..', '.kkwk...', '..kk....', '.kokk...', 'kok.....'],
  def: ['kkkkkkkk', 'kssssssk', 'ksswssnk', 'ksswssnk', '.ksssnk.', '..ksnk..', '...kk...'],
  range: ['...kk...', '..kRRk..', '.kk..kk.', 'kRk..kRk', 'kRk..kRk', '.kk..kk.', '..kRRk..', '...kk...'],
  cd: ['kkkkkkkk', 'kwwwwwwk', '.kyyyyk.', '..kyyk..', '..kyyk..', '.kwyywk.', 'kyyyyyyk', 'kkkkkkkk'],
  load: ['..kkkk..', '.k....k.', '.kkkkkk.', 'kllllllk', 'klwllldk', 'kllllldk', 'kddddddk', '.kkkkkk.'],
  gun: ['........', 'kkkkkkk.', 'klllllwk', 'kddddkk.', 'kddk....', 'kkk.....'],
  star: ['...kk...', '..kyyk..', 'kkkyykkk', 'kyyyyyyk', '.kyyyok.', '.kyokyk.', 'kyk..kok', 'kk....kk'],
  book: ['kkkkkkk.', 'kssswwwk', 'ksswkkwk', 'kssswwwk', 'ksswkkwk', 'kssswwwk', 'kssssssk', 'kkkkkkkk'],
  heal: ['..kkk...', '..kgk...', 'kkkgkkk.', 'kgggggk.', 'kkkgkkk.', '..kgk...', '..kkk...'],
  move: ['...kk...', '..kgek..', '.kggeek.', 'kkkgekkk', '..kgek..', '..kgek..', '..kkkk..'],
  energy: ['....kkk.', '...kcck.', '..kcck..', '.kccckk.', 'kkkccck.', '..kcck..', '.kcck...', '.kkk....'],
  heat: ['...k....', '..kok...', '..koyk..', '.koyyok.', 'koyywyok', 'koywwyok', '.koyyok.', '..kkkk..'],
  burst: ['.k....k.', 'kyk..kyk', '.k....k.', '...kk...', '..kyyk..', '...kk...', '........'],
  heatin: ['...k....', '..kok...', '.koyok..', 'koyyyok.', '.kooook.', '.kkkkkkk', '..kRRRk.', '...kRk..'],
  ammo: ['.k...k..', 'kyk.kyk.', 'kyk.kyk.', 'kok.kok.', 'kok.kok.', 'kdk.kdk.', 'kkk.kkk.'],
  lock: ['..kkkk..', '.kllllk.', '.kk..kk.', 'kyyyyyyk', 'kyykkyok', 'kyykkyok', 'kyyyyook', 'kkkkkkkk'],
  shard: ['...kk...', '..khak..', '.khhaak.', '.khaabk.', 'khaaabbk', '.kaabbk.', '..kabk..', '...kk...'], // Abyss Shard (tint it: ico('shard', violet))
  top: ['...kk...', '..kwwk..', '.kwwwwk.', 'kkkwwkkk', '..kwwk..', 'kkkkkkkk', 'klllllld', 'kkkkkkkk'],
  side: ['kkk.k...', 'kldkwk..', 'kldkwwk.', 'kldwwwwk', 'kldkwwk.', 'kldkwk..', 'kkk.k...'],
  stomp: ['.kkkk...', '.kllk...', '.kllk...', '.klldkk.', 'kllllllk', 'kddddddk', 'kkkkkkkk'],
  backfire: ['..k..k..', '.kRkkRk.', 'kRwRRwRk', '.kRwwRk.', '.kRwwRk.', 'kRwRRwRk', '.kRkkRk.', '..k..k..'],
  resdrain: ['kkkkkkkk', 'kssssssk', 'kswwwwsk', 'kssssssk', '.ksssnk.', '..ksnk..', '...kk...'],
  drain: ['...kkk..', '..kcck..', '.kcck...', 'kccccck.', '..kcck..', '.kkkkkkk', '..kRRRk.', '...kRk..'],
  push: ['k...k...', 'kk..kk..', 'kwk.kwk.', 'kwwkkwwk', 'kwk.kwk.', 'kk..kk..', 'k...k...'],
  pull: ['...k...k', '..kk..kk', '.kwk.kwk', 'kwwkkwwk', '.kwk.kwk', '..kk..kk', '...k...k'],
  pierce: ['.....k..', '.....kk.', 'kkkkkkwk', 'kwwwwwwk', 'kkkkkkwk', '.....kk.', '.....k..'],
  arc: ['..kkk...', '.k...k..', 'k.....k.', 'k.....k.', 'k......k', 'yk.....y', 'yy....yy'],
  regen: ['..kkkk..', '.kcccck.', 'kck..kk.', 'kck.kcck', 'kck..kk.', 'kck.....', '.kcccck.', '..kkkk..'],
  cool: ['...k....', '.k.k.k..', '..kck...', 'kkcwckk.', '..kck...', '.k.k.k..', '...k....'],
  auto: ['.kkkkkk.', 'kwwwwwwk', 'kwkwwkwk', 'kwwwwwwk', 'kwkkkkwk', 'kwwwwwwk', '.kkkkkk.', '..k..k..'],
  pod: [
    '....kkkkkk....',
    '...khhhhhhk...',
    '..khaaaaaabk..',
    '.khawwaaaaabk.',
    '.kaawaaaaaabk.',
    'kkkkkkkkkkkkkk',
    'kyykyykyykyykk',
    'kkkkkkkkkkkkkk',
    '.kaaaaaaaaabk.',
    '.kaaaaaaaaabk.',
    '.kbaaaaaaabbk.',
    '..kbbbbbbbbk..',
    '..kk......kk..',
    '.kkk......kkk.',
  ],
};

// ---------- Hi-res part grids (24 wide, drawn at 2x) ----------
// Every gun, drone, module and special has one; the canvas carries `px = 2`
// so the battle view and mech preview draw it at the 12-wide size, with more detail.

const HI_GRIDS = {
  wp_blaster: [
    '........................',
    '....kkkkkkkkkkkkkk......',
    '...khhhhhhhhhhhhhhk.....',
    '..khhaaaaaaaaaaaaahkkkk.',
    '..kaaaaaaaaaaaaaaaakllkw',
    '..kaawwaaaaaaaaaaaakllkw',
    '..kaaaaaaaaaaaaaaaakllkw',
    '..kbbbbbbbbbbbbbbbbkkkk.',
    '..kbbbbkkkkkkkkkkkkk....',
    '..kbbbbk.kkk............',
    '..kbbbbk.k.k............',
    '..kbbbbkkkk.............',
    '..kbbbbk................',
    '..kkkkkk................',
  ],
  wp_sniper: [
    '......kkkkkkkk..........',
    '......kcwllldk..........',
    '......kkkkkkkk..........',
    '.......kk..kk...........',
    'kkkk..kkkkkkkkk......kkk',
    'khhkkkhhhhhhhhhkkkkkkkhk',
    'kaahhhaaaaaaaaakhhhhhhhw',
    'kaaaaaaaaaaaaaakbbbbbbbw',
    'kbbbbbbbbbbbbbbkkkkkkkbk',
    'kbbbk.kbbkkkkkk......kkk',
    'kbbk..kbbk..............',
    'kbk...kbbk..............',
    'kkk...kkkk..............',
  ],
  wp_omega: [
    '........................',
    '.kkkkkkkkkkkkk........k.',
    'khhhhhhhhhhhllkkkkkkkklk',
    'khhhhhhhhhhhddlllllllldk',
    'kaaaaaaaaaaadddddddddddw',
    'kaabbbbbbaaaddlllllllldk',
    'kaaaaaaaaaaadddddddddddw',
    'kaaaaaaaaaaaddlllllllldk',
    'kbbbbbbbbbbbdddddddddddk',
    'kbbbbbbbbbbbddkkkkkkkkdk',
    '.kbbRRRRRkkkkk........k.',
    '.kbbRwwwRk..............',
    '.kbbRRRRRk..............',
    '.kbbkkkkk...............',
    '.kbbk...................',
  ],
  wp_scythe: [
    '...........k............',
    '.......kkkkwkkkkkkk.....',
    '.....kkwhhhhhhhllllk....',
    '....kwhhaaaaaaalpplk....',
    '...kwhaaaaaaaaallllk....',
    '..khhaaaakkkaaalddhk....',
    '..khaakkk...kklddaak....',
    '.khhak......klddaaak....',
    '.khak......klldkkaak....',
    '.khk......kllddk.kak....',
    '..k......kllddk...k.....',
    '........kllddk..........',
    '........klddk...........',
    '.......klddk............',
    '......klddk.............',
    '.....klddk..............',
    '....klddk...............',
    '....kddk................',
  ],
  wp_emp: [
    '........kkkkkkkk........',
    '......kkhhhhhhhhkk......',
    '....kkhhaaaaaaaahhkk....',
    '...khaaakkkkkkkkaaahk...',
    '..khaakkccwwwwcckkaahk..',
    '..kaakcwkkkkkkkkwckaak..',
    '..kaakcwk.pppp.kwckaak..',
    '..kaakcwkkkkkkkkwckaak..',
    '..kbaakkccwwwwcckkaabk..',
    '...kbaaakkkkkkkkaaabk...',
    '....kkbbaaaaaaaabbkk....',
    '......kkbbbbbbbbkk......',
    '.........kbbbbk.........',
    '.........kbbbbk.........',
    '.......kkkkkkkkkk.......',
  ],
  wp_phoenix: [
    '......kykyk.............',
    '...k.kykokok............',
    '..kykokykykyk...........',
    '...kRkRkRkykok..........',
    '.kkhhhhhhhhkkkkk........',
    'kaahhhhhhhhaooookk......',
    'kbbaaaaaahhhrrrrookk....',
    'kbbaawwaahhhkkkkrroyk...',
    'kbbaawwaaaaaooookkroyk..',
    'kbbaaaaaahhhrrrrookkok..',
    'kbbaaaaaahhhkkkkrrook...',
    'kbbaaaaaaaaaoookkkrryk..',
    'kbbbbbbbbbbbrrrookkkoyk.',
    'kbbbbbbbbbbbkkkrroykkok.',
    '.kkkkkkkkkkk...kkroykk..',
    '.................kkok...',
  ],
  wp_scatter: [
    '........................',
    '........................',
    '......................k.',
    '..kkkkkkkkkkkkkkkkkkkkdk',
    '.khhhhhhhhhhlllllllllldk',
    'kaaaaawaaaaadddddddddddk',
    'kaaaaaaaaaaalllllllllldk',
    'kaaaaaaaaaaadddddddddddk',
    '.kbbbbbbbbbbkkkkkkkkkkdk',
    '..kkbbbkkkkkkaaaaaak..k.',
    '...kbbbk....kbbbbbbk....',
    '..kbbbk......kkkkkk.....',
    '..kbbbk.................',
    '...kkk..................',
  ],
  wp_breacher: [
    '........................',
    '....................kk..',
    '...................klwk.',
    '..kkkkkkkkkkkkkkkkkkllk.',
    '.khhhhhhhhhhllllllllllk.',
    'kaaaaawaaaaaddddddddllwk',
    'kaaaaaaaaaaadtttttttllwk',
    'kaaaaaaaaaaadtttttttllwk',
    'kaaaaaaaaaaaddddddddllk.',
    '.kbbbbbbbbbbkkkkkkkkllk.',
    '..kkbbbkkkkk.......klwk.',
    '...kbbbk............kk..',
    '..kbbbk.................',
    '..kbbbk.................',
  ],
  wp_dragon: [
    '........................',
    '........................',
    '.................kkk....',
    '................kayak...',
    '..kkkkkkkkkkkkkkkaaaokk.',
    '.khhhhhhhhhllllllaaoyook',
    'kaaaaawaaaaddddddkkyooyo',
    'kaaaaaaaaaallllllkkroykk',
    'kaaaaaaaaaaddddddbbbkok.',
    '.kbbbbbbbbbkkkkkkbbbkk..',
    '..kkbbbkkkk.....kbbbk...',
    '...kbbbk.........kkk....',
    '..kbbbk.................',
    '..kbbbk.................',
  ],
  wp_acid: [
    '...kkkkkkkk.............',
    '..kwwwwwwwwk............',
    '..kggggggggk............',
    '..kggggggggk............',
    '..keeeeeeeek............',
    '..kkkkddkkkkk.......kk..',
    '.khhhhhhhhhhhkkkkkkkllk.',
    'kaaaaaaaaaaaalllllllllk.',
    'kaaaaaaaaaaaadddddddllgk',
    'kaaaaaaaaaaaakkkkkkkllke',
    '.kbbbbbbbbbbbk......kkgk',
    '..kkbbbkkkkkk.........k.',
    '...kbbbk.............kgk',
    '..kbbbk...............k.',
    '..kbbbk.................',
  ],
  wp_smg: [
    '........................',
    '..kkkk...............k..',
    '.kllllkkkkkkkk.....kkyk.',
    '..khhhhhhhhhhhkkkkkykkk.',
    '.kaaaaaawaaaaalllllwykyk',
    '.kaaaaaaaaaaaadddddykkk.',
    '.kaaaaaaaaaaaakkkkkkkyk.',
    '..kbbbbbbbbbbbk......k..',
    '...klllkkkbbkk..........',
    '...kdddk.kbbk...........',
    '...kdddkkbbk............',
    '...kdddkkbbk............',
    '...kdddk.kk.............',
    '...kdddk................',
    '....kkk.................',
  ],
  wp_repulsor: [
    '..........kkkskkk.......',
    '.........ksskkkssk......',
    '........kskk.k.kksk.....',
    '.......ksk.kkckk.ksk....',
    '..kkkkkskkkcclcck.ksk...',
    '.khhhhhshhcdddkkckksk...',
    'kaaaaawaaacdddkkck.kk...',
    'kaaaaasaacadddk.kckksk..',
    'kaaaaaaaaacdddkkck.kk...',
    '.kbbbbbsbbcdddkkckksk...',
    '..kkbbbskkkccdcck.ksk...',
    '...kbbbksk.kkckk.ksk....',
    '..kbbbk.kskk.k.kksk.....',
    '..kbbbk..ksskkkssk......',
    '...kkk....kkkskkk.......',
  ],
  wp_rifle: [
    '.......kkkkk............',
    '......kllllck...........',
    '......kdddddk...........',
    '......kkkkkkk...........',
    'kkkkkkhhhhhhhkkkkkkkkkkk',
    'aaaaaaaaaaaaalllllllllll',
    'bbbbbaaaaaaaaddddddddkkk',
    'bbbbbkbbbbbbbkkkkkkkk...',
    'bbbbbkkkkbbkk...........',
    'kkkkk...kbbk............',
    '.......kbbk.............',
    '........kk..............',
  ],
  wp_needler: [
    '........................',
    '.......kkkkk............',
    '......kdddddk...........',
    '......kkkkkkkk....kkkkk.',
    'kkkkkkhhhhhhhhkkkklllllk',
    'aaaaaaaaaaaaaallllwwwwww',
    'bbbbbaaaaaaaaaddddwwwwwk',
    'bbbbbkbbbbbbbbkkkkllllk.',
    'bbbbbkkkkbbkkk....kkkk..',
    'kkkkk...kbbk............',
    '.......kbbk.............',
    '........kk..............',
  ],
  wp_gauss: [
    '........................',
    '........................',
    '..............kk.kk.kk..',
    '......kkkkkkkkcckcckcck.',
    'kkkkkkhhhhhhhksskssksskk',
    'aaaaaaaaaaaaalsslsslssll',
    'bbbbbaaacaaaadssdssdssdd',
    'bbbbbaaaaaaaaksskssksskk',
    'bbbbbkbbbbbbbkssksskssk.',
    'kkkkk.kkkbbkk.kk.kk.kk..',
    '........kbbk............',
    '.......kbbk.............',
    '........kk..............',
  ],
  wp_flamer: [
    '........................',
    '........................',
    '........................',
    '..kkkkkkkkkkkk.......kk.',
    '.khhhhhhhhhhhhkkkkkkkoyk',
    'kaaaaaaaaaaaaallllllkyoo',
    'kaaaaaaaaaaaaaddddddsrok',
    '.kbbbbbbbbbbbbkkkkkkkkk.',
    '..kkkbbbkkkkkkkk........',
    '....kbbbooooooook.......',
    '...kbbbkrrrrrrrrk.......',
    '...kbbbkrrrrrrrrk.......',
    '....kkkkrrrrrrrk........',
    '........kkkkkkk.........',
    '........................',
  ],
  wp_chem: [
    '........................',
    'kkkkkk..................',
    'wwwwwwk.................',
    'gggeeek.................',
    'gggeeekkkkkkkkk......kk.',
    'gggeeehhhhhhhhhkkkkkkoyk',
    'gggeeeaaaaaaaaallllllyoo',
    'gggeeeaaaaaaaaaddddddrok',
    'gggeeebbbbbbbbbkkkkkkkk.',
    'gggeeekkbbbkkkk.........',
    'gggeeekkbbbk............',
    'gggeeekbbbk.............',
    'kdkkkkkbbbk.............',
    'kddddddkkk..............',
    '.kkkkkk.................',
  ],
  wp_cryo: [
    '........................',
    '........................',
    '............k..k........',
    '..kkkkkkkkkkckkck....k..',
    '.khhhhhhhhhkckkckkk.kck.',
    'kaaaaaaaaaawcwwcwwwkkkck',
    'kaaaaaaaaaalcllclllkckkk',
    'kaaaaaaaaaalcllclllcwcwc',
    'kaaaaaaaaaalcllclllkckkk',
    'kaaaaaaaaaadcddcdddkkkck',
    '.kbbbbbbbbbkckkckkk.kck.',
    '..kkbbbkkkkkckkck....k..',
    '...kbbbk....k..k........',
    '..kbbbk.................',
    '...kkk..................',
  ],
  wp_beam: [
    '........................',
    '........................',
    '..............kkk.......',
    '..kkkkkkkkkkkklllk......',
    '.khhhhhhhhhhhhdddkk.....',
    'kaawwwwwwwwaaaddwwrkkkkk',
    'kaaaaaaaaaaaaaddwwRRRRRR',
    'kaaaaaaaaaaaaaddwwrkkkkk',
    '.kbbbbbbbbbbbbdddkk.....',
    '..kkkbbbkkkkkkdddk......',
    '....kbbbk.....kkk.......',
    '...kbbbk................',
    '....kkk.................',
  ],
  wp_siphon: [
    '........................',
    '........................',
    '...................k....',
    '.................kkgkk..',
    '..kkkkkkkkkkk..kkdlgkgkk',
    '.khhhhhhhhhhhkkdldlgkkkg',
    'kaaaaawaaaaaadldldlgk.kk',
    'kaaaaaaaaaaaadldldlgkkgk',
    'kaaaaaaaaaaaadldldlgk.kk',
    '.kbbbbbbbbbbbkkdldlgkkkg',
    '..kkkbbbkkkkk..kkdlgkgkk',
    '....kbbbk........kkgkk..',
    '...kbbbk...........k....',
    '....kkk.................',
  ],
  wp_grapple: [
    '........................',
    '........................',
    '........................',
    '..................kkkk..',
    '..kkkkkkkkk.....kkllllk.',
    '.khhhhhhhhhk...kddkkkklk',
    'kaaaaawaaaakkkkkddkkkkkk',
    'kaaaaaaaaaalllllddlllllw',
    'kaaaaaaaaaakkkkkddkkkkkk',
    '.kbbbbbbbbbk...kddkkkklk',
    '..kkbbbkkkk.....kkllllk.',
    '...kbbbk..........kkkk..',
    '..kbbbk.................',
    '...kkk..................',
  ],
  wp_shredder: [
    '................k.......',
    '...............kwk......',
    '............kkkklkkkk...',
    '...........kwlllllllwk..',
    '..kkkkkkkk.klllldllllk..',
    '.khhhhhhhhkllldddddlllk.',
    'kaaaaaaaaaklldddddddllk.',
    'kaaaaaaaaakllddaaaddllk.',
    'kaaaaaaaaawldddaaadddlwk',
    'kaaaaaaaaakllddaaaddllk.',
    '.kbbbbbbbbklldddddddllk.',
    '..kkbbbkkkkllldddddlllk.',
    '...kbbbk...klllldllllk..',
    '..kbbbk....kwlllllllwk..',
    '..kbbbk.....kkkklkkkk...',
    '...kkk.........kwk......',
  ],
  wp_tesla: [
    '..............kwk.......',
    '.............kwwwkk.k...',
    '............kwwcwwckck..',
    '...........kddwwwdkckk.k',
    '...........klllwllkkkckc',
    '...........kddddddk..kck',
    '...........kllllllk.kck.',
    '...........kddddddk..k..',
    '..kkkkkkkkkkllllllk.....',
    '.khhhhhhhhhbbbbbbbbk....',
    'kaaaaawaaaabbbbbbbbk....',
    'kaaaaaaaaaaakkkkkkk.....',
    'kaaaaaaaaaaak...........',
    '.kbbbbbbbbbbk...........',
    '..kkbbbkkkkk............',
    '...kbbbk................',
  ],
  wp_heatray: [
    '...............k........',
    '..............klk.......',
    '.............kllk.......',
    '............klllkk.k....',
    '..kkkkkkkkkkllldkokok...',
    '.khhhhhhhhhlllddkkokok..',
    'kaaaaawaaaalldddkkkkkk..',
    'kaaaaaaaaaaldddykokokok.',
    'kaaaaaaaaaalldddkkokok..',
    '.kbbbbbbbbblllddkkkkk...',
    '..kkbbbkkkkkllldkokok...',
    '...kbbbk....klllkkokok..',
    '..kbbbk......kllk.k.k...',
    '..kbbbk.......klk.......',
    '...kkk.........k........',
  ],
  wp_scorcher: [
    '........................',
    '........................',
    '............kk.kk.kk....',
    '...........kyokyokyokkk.',
    '..kkkkkkkkkkokkokkokkllk',
    '.khhhhhhhhlllllllllllllk',
    'kaaaaawaaadddddddddddllk',
    'kaaaaaaaaaddoddoddoddllk',
    'kaaaaaaaaadddddddddddllk',
    'kaaaaaaaaadddddddddddllk',
    '.kbbbbbbbbkkkkkkkkkkkllk',
    '..kkbbbkkk...........kk.',
    '...kbbbk................',
    '..kbbbk.................',
    '...kkk..................',
  ],
  wp_ionizer: [
    '........................',
    '........................',
    '..............kkkkkkk...',
    '............kklllllllk..',
    '..kkkkkkkkkkddkkkkkkklk.',
    '.khhhhhhhhhhddk.kccckk..',
    'kaaaaawaaaaaddkkccwcck..',
    'kaaaaaaaaaaaddkkcwwwck..',
    'kaaaaaaaaaaaddkkccwcck..',
    '.kbbbbbbbbbbddk.kccckk..',
    '..kkbbbkkkkkddkkkkkkklk.',
    '...kbbbk....kklllllllk..',
    '..kbbbk.......kkkkkkk...',
    '..kbbbk.................',
    '...kkk..................',
  ],
  wp_impact: [
    '........................',
    '..............kkkkkkk...',
    '.............khhhhhhbk..',
    '..kkkkkkkk...kaaaaaabkk.',
    '.khhhhhhhhk..kaaaaaabddk',
    'kaaaaawaaakkkkaaaaaabdll',
    'kaaaaaaaaawwwwaaaaaabdll',
    'kaaaaaaaaallllaaaaaabdll',
    'kaaaaaaaaallllaaaaaabdll',
    'kaaaaaaaaakkkkaaaaaabdll',
    '.kbbbbbbbbk..kaaaaaabddk',
    '..kkbbbkkk...kaaaaaabkk.',
    '...kbbbk.....kbbbbbbbk..',
    '..kbbbk.......kkkkkkk...',
    '..kbbbk.................',
    '...kkk..................',
  ],
  wp_blowtorch: [
    '........................',
    '........................',
    '........................',
    '.kkkkkkk................',
    'kyyyyyyykkkkkk....k.....',
    'koooooookhhhhhkkkkskkkk.',
    'koooooooaaaaaalllwcscsnk',
    'koooooooaaaaaakkkkskkkk.',
    'koooooookbbbbbk...k.....',
    'krrrrrrrkkkbbk..........',
    '.kkkkkkk..kbbk..........',
    '.........kbbk...........',
    '..........kk............',
  ],
  wp_rupturer: [
    '........................',
    '...kkkkkk...............',
    '..kwwwwwwk..............',
    '..kccnccck..............',
    '..kcccncck..............',
    '..kcccccckk.............',
    '.khhhhhhhhhkkkkkkkk.....',
    'kaaaaaaaaaawwwwwdddkkk.k',
    'kaaaaaaaaaalllllddddwwkc',
    'kaaaaaaaaaallllldddkkk.k',
    '.kbbbbbbbbbkkkkkkkk.....',
    '..kkbbbkkkk.............',
    '...kbbbk................',
    '..kbbbk.................',
    '...kkk..................',
  ],
  wp_thermal: [
    '........................',
    '........................',
    '........................',
    '..kkkkkkkk..............',
    '.khhhhhhhhkkkkkkkkkkkk..',
    'kaaaawaaaawwwwwwwwwwookk',
    'kaaaaaaaaallllllllllyoyy',
    'kaaaaaaaaaddddddddddookk',
    '.kbbbbbbbbkkkkkkkkkkkk..',
    '..kkbbbkkk..............',
    '...kbbbk................',
    '..kbbbk.................',
  ],
  wp_spark: [
    '........................',
    '........................',
    '....................k.k.',
    '....kkkkkkkkk....k.kykyk',
    '...khhhhhhhhhkkkkckywyk.',
    '..kaaaaaaaaaalllcwckyk..',
    '..kaaaaaaaaaalllkck.kk..',
    '...kbbbbbbbbbkkk.k..kck.',
    '....kkbbbkkkk........k..',
    '.....kbbbk..............',
    '....kbbbk...............',
    '....kbbbk...............',
    '.....kkk................',
  ],
  wp_leech: [
    '........................',
    '........................',
    '........................',
    '..........k.k.k.k.kkkk..',
    '..kkkkkkkkgkgkgkgkdddwk.',
    '.khhhhhhhhgegegegedddwwk',
    'kaaaaawaaagegegegedddkk.',
    'kaaaaaaaaagegegegedddk..',
    'kaaaaaaaaagegegegedddkk.',
    '.kbbbbbbbbgegegegedddwwk',
    '..kkbbbkkkgkgkgkgkdddwk.',
    '...kbbbk..k.k.k.k.kkkk..',
    '..kbbbk.................',
    '..kbbbk.................',
    '...kkk..................',
  ],
  wp_gridbreaker: [
    '........................',
    '..............kkkkkkkk..',
    '.............khhhhhhhhk.',
    '.............kaaaaaaaak.',
    '.............kaaaayaaak.',
    '.............kaaayaaaak.',
    '..kkkkkkkk...kaaayaaaak.',
    '.khhhhhhhhkkkkaayyyyaak.',
    'kaaaaaaaaaddddaaaayaaak.',
    'kaaaaaaaaaddddaaaayaaak.',
    '.kbbbbbbbbkkkkaaayaaaak.',
    '..kkbbbkkk...kaaayaaaak.',
    '...kbbbk.....kaayaaaaak.',
    '..kbbbk......kaaaaaaaak.',
    '..kbbbk......kbbbbbbbbk.',
    '...kkk........kkkkkkkk..',
  ],
  wp_capdump: [
    '........................',
    '...kkk.kkk.kkk..........',
    '..kwwwkwwwkwwwk...kkk...',
    '..kccckccckccck..klllk..',
    '..kccckccckccckkkkdddkk.',
    '.khhhhhhhhhhhhhhhhdddkck',
    'kaaaaaaaaaaaaaaaaadddyk.',
    'kaaaaaaaaaaaaaaaaadddwyk',
    'kaaaaaaaaaaaaaaaaadddyk.',
    '.kbbbbbbbbbbbbbbbbdddkck',
    '..kkbbbkkkkkkkkkkkdddkk.',
    '...kbbbk.........kdddk..',
    '..kbbbk...........kkk...',
    '..kbbbk.................',
    '...kkk..................',
  ],
  wp_magma: [
    '........................',
    '........................',
    '......kkkkkkkkkk.kkk....',
    '.....khhhhhhhhhhkhhhk...',
    '.kkkkaaaaaaaaaaaaaaaak..',
    'kaaaaaaoaaaaaoaaaobbk...',
    'kbbbbaaaoaaaayaaahhhk...',
    'kbbbbaaayaaaaaoaaaaaak..',
    'kbbbbaaaaoyaaaaaaobbk...',
    'kbbbbaaaaaaooaaaahhhk...',
    'kbbbbaaoaaaahhhhaaaaak..',
    'kbbbbaoaaaaabbbbbobbk...',
    'kbbbbaaaaaaabbbbbhhhk...',
    '.kkkkkbbbbbbbbbbbaaaak..',
    '......kkkkkkkkkkkbbbk...',
    '.................kkk....',
  ],
  wp_breaker: [
    '........................',
    '.............kkkkkkkk...',
    '............kllllllllkk.',
    '............kddddddddllk',
    '..kkkkkkk...kddaaaaddllk',
    '.khhhhhhhkkkkddddddddllw',
    'kaaaaaaaawwwwddddddddllw',
    'kaaaaaaaallllddddddddllw',
    'kaaaaaaaallllddaaaaddllw',
    'kaaaaaaaallllddddddddllw',
    '.kbbbbbbbkkkkddddddddllw',
    '..kkbbbkk...kddaaaaddllk',
    '...kbbbk....kddddddddllk',
    '..kbbbk.....kttttttttkk.',
    '..kbbbk......kkkkkkkk...',
    '...kkk..................',
  ],
  wp_recoil: [
    '........................',
    '........................',
    '........................',
    'k.k.k.k..kkkkkkkk.....kk',
    'dkdkdkdkkhhhhhhhhkkkkkll',
    'dldldldlaaaaaaaaalllllll',
    'dldldldlaaaaaaaaadddddll',
    'dldldldlaaaaaaaaadddddll',
    'dldldldlaaaaaaaaadddddll',
    'dldldldlaaaaaaaaadddddll',
    'dkdkdkdkkbbbbbbbbkkkkkll',
    'k.k.k.k..kkkbbbkk.....kk',
    '...........kbbbk........',
    '..........kbbbk.........',
    '...........kkk..........',
  ],
  wp_dynamo: [
    '......kkkkk.............',
    '.....kllwllk............',
    '....kllldlllk...........',
    '...klldddddllk..........',
    '...kllddcddllk.......k.k',
    '...kwddcccddwk......kckc',
    '..kkllddcddllkkk...kcwck',
    '.khhlldddddllhhhkkkkkck.',
    'kaaaallldlllaaaallllllk.',
    'kaaaaallwllaaaaaddddddk.',
    'kaaaaaaaaaaaaaaakkkkkk..',
    '.kbbbbbbbbbbbbbbk.......',
    '..kkkbbbkkkkkkkk........',
    '....kbbbk...............',
    '...kbbbk................',
    '....kkk.................',
  ],
  wp_mortar: [
    '........................',
    '................kk......',
    '...............kllk.....',
    '..............khllk.....',
    '............kkhallk.....',
    '..........kkhhaallk.....',
    '.........khhaaaallk.....',
    '.......kkhaaaaabllk.....',
    '.....kkhhaaaaabkllk.....',
    '....khhaaaaabbk.kk......',
    '....kaaaaabbkk..........',
    '....kaaatttk............',
    '..kkkaabtttkkkkk........',
    '.klllbblllllllllk.......',
    '.kddddddddddddddk.......',
    '..kkkkkkkkkkkkkk........',
  ],
  wp_arcmortar: [
    '...................k.k..',
    '...............kk.kckck.',
    '..............kllk.kckk.',
    '..............kllk.kwkck',
    '............kkhllk.kckk.',
    '..........kkhhallk..kck.',
    '.........khhaaallk...k..',
    '.......kkhaaaaallk......',
    '.....kkhhaaaaabllk......',
    '....khhaaaaabbkkk.......',
    '....kaaaaabbkk..........',
    '....kaaatttk............',
    '..kkkaabtttkkkkk........',
    '.klllbblllllllllk.......',
    '.kddddddddddddddk.......',
    '..kkkkkkkkkkkkkk........',
  ],
  wp_concussion: [
    '..............kkkddk....',
    '.............kllkkkdk...',
    '............kkkklkkdk...',
    '...........kllwkklkkdk..',
    '..........kkllkwkklkdk..',
    '........kkhhllkkwklkkk..',
    '.......khhaallkkwklkkdk.',
    '.....kkhaaaallkkwklkkk..',
    '...kkhhaaaaallkwkklkdk..',
    '..khhaaaaabbllwkklkkdk..',
    '..kaaaaabbkkkkkklkkdk...',
    '..kaaaabkk...kllk.kdk...',
    '.kkaabbkkkkkkkkk...k....',
    'kllbblllllllllk.........',
    'kdddddddddddddk.........',
    '.kkkkkkkkkkkkk..........',
  ],
  wp_minelauncher: [
    '........................',
    '...................k....',
    '..................klk...',
    '..............kkk..k..k.',
    '.kkkkkkkkkkkkkdllkkdkklk',
    'khhhhhhhhhhhhhdlkdddddk.',
    'kaaaaaaaaaaaaadlkdRRRdkk',
    'kaaaaaaaaaaaaallddRwRddl',
    'kaaaaaaaaaaaaadlkdRRRdkk',
    'kbbbbbbbbbbbbbdlkdddddk.',
    '.kkkkkkkkkkkkkdllkkdkklk',
    '..kdddddddk...kkk..k..k.',
    '..kdddddddk.......klk...',
    '...ktttttk.........k....',
    '....kkkkk...............',
  ],
  wp_rocket: [
    '........................',
    '........................',
    '...............kk.......',
    'kkkkkkkkkkkkkkkdlk......',
    'hhhbhhhhhhhhhhhdlkkkkk..',
    'aaabaaaaaaaaaaadlwwwwrk.',
    'aaabaaaaaaaaaaadlllllrrk',
    'aaabaaaaaaaaaaadlllllrk.',
    'bbbbbbbbbbbbbbbdlkkkkk..',
    'kkkkkkkkkkkkkkkdlk......',
    '....kdddddddk..kk.......',
    '....kdddddddk...........',
    '.....ktttttk............',
    '......kkkkk.............',
  ],
  wp_cluster: [
    '........................',
    '......................k.',
    '.................k...kok',
    '.............kk.kok.koyo',
    'kkkkkkkkkkkkkdlkoyokkkok',
    'hhhhhhhhhhhhhdlkkokkokk.',
    'aaaaaaaaaaaaadlk.kkoyok.',
    'aaaaaaaaaaaaadlk.k.kok..',
    'aaaaaaaaaaaaadlkkok.kk..',
    'bbbbbbbbbbbbbdlkoyokkok.',
    'kkkkkkkkkkkkkdlkkokkoyok',
    '...kdddddddk.kk..k..kok.',
    '...kdddddddk.........k..',
    '....ktttttk.............',
    '.....kkkkk..............',
  ],
  wp_napalm: [
    '........................',
    '....kkkkkkk.............',
    '...koooooook............',
    '...krrrrrrrk..kk........',
    'kkkkrrrrrrrkkkdlk.k.....',
    'hhhhhhhhhhhhhhdlkkokk...',
    'aaaaaaaaaaaaaadlkoyook..',
    'aaaaaaaaaaaaaadlkyooyok.',
    'aaaaaaaaaaaaaadlkroykk..',
    'bbbbbbbbbbbbbbdlkkkok...',
    'kkkkkkkkkkkkkkdlk..k....',
    '...kdddddddk..kk........',
    '...kdddddddk............',
    '....ktttttk.............',
    '.....kkkkk..............',
  ],
  wp_thermite: [
    '........................',
    '........................',
    '........................',
    '............kkkkkkkkk...',
    'kkkkkkkkkkkkdlwwwwwwwk..',
    'hhhhhhhhhhhhdlyyyyyyykk.',
    'aaaaaaaaaaaadlyoooooyddk',
    'aaaaaaaaaaaadlyyyyyyyddk',
    'aaaaaaaaaaaadlyoooooyddk',
    'bbbbbbbbbbbbdlyyyyyyykk.',
    'kkkkkkkkkkkkdloooooook..',
    '...kdddddddkkkkkkkkkk...',
    '...kdddddddk............',
    '....ktttttk.............',
    '.....kkkkk..............',
  ],
  wp_harpoon: [
    '........................',
    '........................',
    '..........kk.......k....',
    'kkkkkkkkkkdlk.....klk...',
    'hhhhhhhhhhdlk......klk..',
    'aaaaaaaaaadlkkkkkkkkkwkk',
    'aaaaaaaaaadllllllllllwwl',
    'aaaaaaaaaadldddddddddwwk',
    'bbbbbbbbbbdlkkkkkkkkkwk.',
    'kkkkkkkkkkdlk......kdk..',
    '..kdddddddkk......kdk...',
    '..kdddddddk........k....',
    '...ktttttk..............',
    '....kkkkk...............',
  ],
  wp_missiles: [
    '........................',
    '.kkkkkkkkkkkkkkkkkkk....',
    'khhhhhhhhhhhhhhhhhhhkk..',
    'kaaaaaaaaaaaaaaaaaaaddk.',
    'kaaaattwaattwaattwaaddk.',
    'kaaaatRtaatRtaatRtaaddk.',
    'kaaaatttaatttaatttaaddk.',
    'kaaaaaaaaaaaaaaaaaaaddk.',
    'kaaaattwaattwaattwaaddk.',
    'kaaaatRtaatRtaatRtaaddk.',
    'kaaaatttaatttaatttaaddk.',
    'kaaaaaaaaaaaaaaaaaaaddk.',
    'kbbbbbbbbbbbbbbbbbbbkk..',
    '.kkkkddddddddkkkkkkk....',
    '....kddddddddk..........',
    '.....kttttttk...........',
  ],
  wp_rail: [
    '........................',
    '........kkkkkkkkkkkkkkkk',
    '.kkkkkkkwwwwwwwwwwwwwwww',
    'khhhhhhhllllllllllllllll',
    'aaaaaaaakkkkkkkkkkkkkkkk',
    'aaaaaaaakkssssccccsssswk',
    'aaaaaaaakkkkkkkkkkkkkkkk',
    'aaaaaaaallllllllllllllll',
    'kbbbbbbbdddddddddddddddd',
    '.kdddddddkkkkkkkkkkkkkkk',
    '.kdddddddk..............',
    '..ktttttk...............',
    '...kkkkk................',
  ],
  wp_nova: [
    '........................',
    '........................',
    '....................k...',
    '...................kyk..',
    '.kkkkkkk..........k.k.k.',
    'khhhhhhhkkkkkkkkkkykykyk',
    'aaaaaaaawwwwwwwwwwkyyykk',
    'aaaaaaaallllllllylyywyyw',
    'aaaaaaaallllllllllkyyykk',
    'aaaaaaaaddddddddddykykyk',
    'kbbbbbbbkkkkkkkkkkk.k.k.',
    '.kdddddddk.........kyk..',
    '.kdddddddk..........k...',
    '..ktttttk...............',
    '...kkkkk................',
  ],
  wp_howitzer: [
    '................kkhalllk',
    '..............kkhhaalllk',
    '.............khhaaablllk',
    '......kkkkkkkhaaaabkkkk.',
    '.....khhhhhhhaaabbk.....',
    '.....kaaaaaaaabbkk......',
    '.....kaaaaaaabkk........',
    '...kkkaaaaabbk..........',
    '..kbhhaaaaabbk..........',
    '..kbaaaabbbbbk..........',
    '..kbaabbbbbbbk..........',
    '...kbblddkkkk...........',
    '..kddlllddk.............',
    '...kddlddk..............',
    '...kdddddk..............',
    '....kkdkk...............',
  ],
  wp_meltdown: [
    '........................',
    '.kkkkkkkkkkkk...........',
    'khhhhhhhhhhhhk..........',
    'kaaaaaaaaaaaak.......kk.',
    'kaaaaaooaaaaakkkkkkkkllk',
    'kaaaaooooaaaallllllllllk',
    'kaaaoyyyyoaaaddddddddllk',
    'kaaaoywwyoaaadoooooodllk',
    'kaaaoyyyyoaaaddddddddllk',
    'kaaaaooooaaaaddddddddllk',
    'kaaaaaooaaaaakkkkkkkkllk',
    'kaaaaaaaaaaaak.......kk.',
    'kbbbbbbbbbbbbk..........',
    '.kkddddddddkk...........',
    '..kddddddddk............',
    '...kttttttk.............',
  ],
  wp_blackout: [
    '........................',
    '........................',
    '........................',
    '................kkkkk...',
    '.kkkkkkkkkk....kpppppk..',
    'khhhhhhhhhhkkkkppqqqppk.',
    'aaaaaaaaaaadddppqqkqqppk',
    'aaaaaaaaaaadddpqqwkkqqpk',
    'aaaaaaaaaaadddpqkkkkkqpk',
    'aaaaaaaaaaadddpqqkkkqqpk',
    'aaaaaaaaaaadddppqqkqqppk',
    'kbbbbbbbbbbkkkkppqqqppk.',
    '.kkkkkkkkkk....kpppppk..',
    '..kddddddddk....kkkkk...',
    '..kddddddddk............',
    '...kttttttk.............',
  ],
  wp_flak: [
    '...................klkk.',
    '..................kkklwk',
    '...............kkkllkwk.',
    '.............kklllddkklk',
    '.......k..kkklldddkk..k.',
    '....kkkakklllddkkkllk...',
    '...kaaaaaadddkklllddk...',
    '..kaaaaaaaaaklldddkk....',
    '..kaaaaaaalllddkkk......',
    '..kaaaaaaadddkk.........',
    '.kbbbbbbbbbbbk..........',
    '.kkaaaaaaaaakk..........',
    'klllllllllllllk.........',
    'kdddddddddddddk.........',
    'kdddddddddddddk.........',
    '.kkkkkkakkkkkk..........',
  ],
  wp_arcturret: [
    '.......kck..............',
    '.......klk..............',
    '.......klk..............',
    '.......klk.............k',
    '.......klk...........kkc',
    '......kklakkk.......kckk',
    '.....kaaaaaaak.......kck',
    '....kaaawwwaaakkkkkkkkk.',
    '...kaaaawwwaaalllllllck.',
    '...kaaaaaaaaaadddddddkk.',
    '...kaaaaaaaaaaakkkkkkkck',
    '..kbbbbbbbbbbbbbk.....kc',
    '.klllllllllllllllk.....k',
    '.kdddddddddddddddk......',
    '.kdddddddddddddddk......',
    '..kkkkkkkkkkkkkkk.......',
  ],
  wp_inferno: [
    '........................',
    '...............k........',
    '...........kkkkokk......',
    'kkkkkkkkkkkllloyook.....',
    'hhhhhhhhhhhdddyooyok....',
    'aaaaaaaaaaadddroykk.....',
    'aarrrrrraaadddoyook.....',
    'aarooooraaadddyooyok....',
    'aarooooraaadddroykk.....',
    'aarrrrrraaadddoyook.....',
    'aaaaaaaaaaadddyooyok....',
    'bbbbbbbbbbbdddroykk.....',
    'kkkkkkkkkkkdddkkok......',
    '.kddddddddkkkk..k.......',
    '.kddddddddk.............',
    '..kttttttk..............',
  ],
  wp_supercon: [
    '........................',
    '..k.....k....k..........',
    '.kwkkkkkwkkkkwk.........',
    'khhchhchhchhchhk........',
    'kaacaacaacaacaakkkk.....',
    'kaacaacaacaacaallllkkkkk',
    'kaacaacaacaacaaddddwwwww',
    'kaacaacaacaacaaddddRRRRR',
    'kaacaacaacaacaaddddkkkkk',
    'kaacaacaacaacaakkkk.....',
    'kbbcbbcbbcbbcbbk........',
    '.kkkkkkkkkkkkkk.........',
    '..kddddddddk............',
    '..kddddddddk............',
    '...kttttttk.............',
  ],
  sp_charge: [
    '........................',
    '........................',
    '............kkkkkkkkkk..',
    '.......kkkkkhhhhhhhhhhk.',
    '.....kkoyyllaaaaaaaaaakk',
    '..kkkoooyyddaawwwwwwaall',
    '.krroooywwddaaaaaaaaaall',
    '.kyyyyyywwddaaaaaaaaaall',
    '..kkoooywwddaaaaaaaaaall',
    '....kkkoyyddaaaaaaaaaakk',
    '.......kkykkbbbbbbbbbbk.',
    '.........k..kkkkkkkkkk..',
    '........................',
    '........................',
  ],
  sp_retro: [
    '........................',
    '........................',
    '..kkkkkkkkkk............',
    '.khhhhhhhhhhkkkkk.......',
    'kkaaaaaaaaaallyyokk.....',
    'llaawwwwwwaaddyyoookkk..',
    'llaaaaaaaaaaddwwyooorrk.',
    'llaaaaaaaaaaddwwyyyyyyk.',
    'llaaaaaaaaaaddwwyoookk..',
    'kkaaaaaaaaaaddyyokkk....',
    '.kbbbbbbbbbbkkykk.......',
    '..kkkkkkkkkk..k.........',
    '........................',
    '........................',
  ],
  sp_ram: [
    '...................kk...',
    '..................kwlkk.',
    '..........kkkkkkkkkwlwlk',
    '.....kkkkkhhhhhhhhhwlkk.',
    '...kkoyyllaaaaaaaaawlkk.',
    'kkkoooyyddaaaaaaaaawlwlk',
    'rroooywwddaaaaaaaaawlkk.',
    'yyyyyywwddaaaaaaaaawlkk.',
    'kkoooywwddaaaaaaaaawlwlk',
    '..kkkoyyddaaaaaaaaawlkk.',
    '.....kkykkbbbbbbbbbwlkk.',
    '.......k..kkkkkkkkkwlwlk',
    '..................kwlkk.',
    '...................kk...',
  ],
  sp_teleport: [
    '.........kkkkkkk........',
    '........khhhhhhhk.......',
    '.......khhhhhhhhhk....k.',
    '..k...kaabbbbbbbaak..kwk',
    '.kwk.kaabbpppppbbaak..k.',
    '..k..kabbppphpppbbak....',
    '....kaabbpphhhppbbaak...',
    '....kaabpphhwhhppbaak...',
    '....kaabpphwwwhppbaak...',
    '....kaabpphhwhhppbaak...',
    '.k..kaabbpphhhppbbaak...',
    'kwk..kabbppphpppbbak.k..',
    '.k...kaabbpppppbbaakkwk.',
    '......kaabbbbbbbaak..k..',
    '.......kaaabbbaaak......',
    '........kaaaaaaak.......',
  ],
  sp_blink: [
    '........................',
    '...............k........',
    '..............kak.......',
    '..............kak.......',
    '............k.kak.k.....',
    '...........khkkakkhk....',
    '..k.k.k.....khkakhk.....',
    '.kbkbkbk.kkkkkhahkkkkk..',
    '.kbkbkbkkaaaaaaaaaaaaak.',
    '.kbkbkbk.kkkkkhahkkkkk..',
    '..k.k.k.....khkakhk.....',
    '...........khkkakkhk....',
    '............k.kak.k.....',
    '..............kak.......',
    '..............kak.......',
    '...............k........',
  ],
  sp_hook: [
    '.................k......',
    '................klk.....',
    '..............kklklk....',
    '.............kllk.klk...',
    '.............kllk..k....',
    '....kkkkk....kllk...k...',
    '...kbbbbbk...kllkkkklk..',
    '..kbbbabbbkkkklllllllwk.',
    '.kbbaaaaabaaaalllllllk..',
    '.kbbabbbabbkkkllkkkklk..',
    '.kbaabbbaabk.kllk...k...',
    '.kbbabbbabbk.kllk..k....',
    '.kbbaaaaabbk.kllk.klk...',
    '..kbbbabbbk...kklklk....',
    '...kbbbbbk......klk.....',
    '....kkkkk........k......',
  ],
  sp_tether: [
    '..............kkkkkkkk..',
    '...........kkkahhhhhhhk.',
    '..........kaaaaaaaawwwk.',
    '.........kaaaaaaaaawwwk.',
    '........kaaaaaaaakkkkkk.',
    '.......kaaaakkkkk....kck',
    'kk.....kaaak..........kk',
    'ddkkkkkkaaak..........kc',
    'ddllllllaaak..........kk',
    'ddkkkkkkaaak.........kck',
    'kk.....kaaak..........k.',
    '.......kaaaakkkkk....kck',
    '........kaaaaaaaakkkkkk.',
    '.........kaaaaaaaaawwwk.',
    '..........kaaaaaaaawwwk.',
    '...........kkkaaaaawwwk.',
  ],
  sp_winch: [
    '........................',
    '........................',
    '.kkkkkkkkk..............',
    'klllllllllk......k......',
    'kdddddddddk.....khk.....',
    'kdaaaaaaadk......khkk...',
    'kdddddddddk......kaaakk.',
    'kdaaaaaaadkkkkkkkkaaaaak',
    'kdddddddddllllllllaaaaaw',
    'kdaaaaaaadkkkkkkkkaaaaak',
    'kdddddddddk......kaaakk.',
    'kdaaaaaaadk......kbkk...',
    'kdddddddddk.....kbk.....',
    'ktttttttttk......k......',
    '.kkkkkkkkk..............',
    '........................',
  ],
  dr_gnat: [
    '........................',
    '....kkkkkk....kkkkkk....',
    '...kllllllk..kllllllk...',
    '....kkkdkk....kkdkkk....',
    '......kdkkkkkkkkdk......',
    '.......khhhhhhhhk.......',
    '......kaaaawkwaaak......',
    '......kaaaawwwaaak......',
    '......kbbbbbbbbbbk......',
    '.......kkkkdddkkk.......',
    '..........kdddk.........',
    '...........kdk..........',
    '............k...........',
    '........................',
  ],
  dr_firefly: [
    '........................',
    '....kkkkkk....kkkkkk....',
    '...kllllllk..kllllllk...',
    '....kkkdkk....kkdkkk....',
    '......kdkkkkkkkkdk......',
    '.......khhhhhhhhk.......',
    '......kaaaayyyaaak......',
    '......kaaaayyyaaak......',
    '......kbbbbbbbbbbk......',
    '.......kkkywwwykk.......',
    '.........kyyyyyk........',
    '.........kkkokkk........',
    '........kok.k.kok.......',
    '.........k.kok.k........',
    '............k...........',
  ],
  dr_hornet: [
    '..kkkkkk........kkkkkk..',
    '.kllllllk......kllllllk.',
    '..kkkdkk........kkdkkk..',
    '....kdkkkkkkkkkkkkdk....',
    '.....khhhhhhhhhhhhk.....',
    '....kaakkaRwRRkabbak....',
    '....kaakkaRRRRkabbak....',
    '....kaakkabbakkabbak....',
    '....kbbbbbbbbbbbbbbk....',
    '.....kkkkkbbbbbkkkk.....',
    '.........kbbbbbk........',
    '..........kyyyk.........',
    '..........kyyyk.........',
    '...........kyk..........',
    '...........kwk..........',
    '............k...........',
  ],
  dr_medic: [
    '..kkkkkk........kkkkkk..',
    '.kllllllk......kllllllk.',
    '..kkkdkk........kkdkkk..',
    '....kdkkkkkkkkkkkkdk....',
    '.....khhhhhhhhhhhhk.....',
    '....kaaaaaawwaaaaaak....',
    '....kaaaawwRRwwaaaak....',
    '....kaaaawwRRwwaaaak....',
    '....kaaaaaawwaaaaaak....',
    '....kaaaaaawwaaaaaak....',
    '....kbbbbbbbbbbbbbbk....',
    '.....kkkddddddddkkk.....',
    '.......kddddddddk.......',
    '........kkkkkkkk........',
    '........................',
  ],
  dr_static: [
    '.....kck........kck.....',
    '..kkkklk........klkkkk..',
    '.kllllllk......kllllllk.',
    '..kkkdlk........kldkkk..',
    '....kdlkkkkkkkkkkldk....',
    '.....khhhhhhhhhhhhk.....',
    '....kaaaancccccnaaak....',
    '....kaaaannnnnnnaaak....',
    '....kaaaaaaaaaaaaaak....',
    '....kbbbbbbbbbbbbbbk....',
    '.....kkkkkkkkkkkkkk.....',
    '........kck.kkck........',
    '.........kckckkck.......',
    '........kck.kkck........',
    '.........k.kckk.........',
    '............k...........',
  ],
  dr_coolant: [
    '..kkkkkk........kkkkkk..',
    '.kllllllk......kllllllk.',
    '..kkkdkk........kkdkkk..',
    '....kdkkkkkkkkkkkkdk....',
    '.....khhhhhhhhhhhhk.....',
    '....kaaaaacawacaaaak....',
    '....kaaaaaaawaaaaaak....',
    '....kaaaawwwwwwwaaak....',
    '....kaaaaaaawaaaaaak....',
    '....kaaaaacawacaaaak....',
    '....kbbbbbbbbbbbbbbk....',
    '.....kkkkkkkkkkkkkk.....',
    '.......kck..k..kck......',
    '........k..kck..k.......',
    '............k...........',
  ],
  dr_guardian: [
    '............k...........',
    '.........kkkgkkk........',
    '.......kkgggggggkk......',
    '....kkkggkkkkkkkggkk....',
    '...kllggllk..klllgglk...',
    '....kkgdkk....kkdkgk....',
    '....kgkdkkkkkkkkdkkgk...',
    '....kgkkhhhhhhhhk.kgk...',
    '....kgkaaaawwwaaakkgk...',
    '...kggkaaaawwwaaakkggk..',
    '....kgkaaaaaaaaaakkgk...',
    '....kgkbbbbbbbbbbkkgk...',
    '....kgkkkkkkkkkkk.kgk...',
    '.....k.............k....',
    '........................',
    '........................',
  ],
  dr_reaper: [
    '........................',
    '........................',
    '..kkkkkk....kkkkkk......',
    '.kllllllk..kllllllk.....',
    '..kkkdkk....kkdwkkk.....',
    '....kdkkkkkkkkdwwwwkk...',
    '.....khhhhhhhhkppppwwk..',
    '....kaaaaRwRaaakkkkpwwk.',
    '....kaaaaRRRaaak...kpwk.',
    '....kaaaaaaaaaak....kpwk',
    '....kbbbbbbbbbbk....kpwk',
    '.....kkkkkkkkkk.....kpwk',
    '....................kpww',
    '.....................kkk',
    '........................',
    '........................',
  ],
  dr_seraph: [
    '..........kyyyk.........',
    '.........kykkkyk........',
    '........kyk...kyk.......',
    '........kyk...kyk.......',
    '.........k.....k........',
    '.....kk.kkkkkkkk..kk....',
    '...kkwlkhhhhhhhhkklwkk..',
    '.kkwlwlaaaayyyaaaklwlwkk',
    'kwlwlwlaaaaywyaaaklwlwlw',
    'kwlwlwlaaaayyyaaaklwlwlw',
    '.kkklwlaaaaaaaaaaklwlkkk',
    '....kkkbbbbbbbbbbkkkk...',
    '.......kkkkkkkkkk.......',
    '........................',
    '........................',
    '........................',
  ],
  md_physres: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaattttllllllllttttaak.',
    '.kaattttllllllllttttaak.',
    '.kaattttllwwwwllttttaak.',
    '.kaattttllwwwwllttttaak.',
    '.kaattttllwwwwllttttaak.',
    '.kaattttlllwwlllttttaak.',
    '.kaatttttlllllltttttaak.',
    '.kaattttttllllttttttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_heatres: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaattttoooooooottttaak.',
    '.kaattttoooooooottttaak.',
    '.kaattttoooyoooottttaak.',
    '.kaattttoooyyooottttaak.',
    '.kaattttoooyoooottttaak.',
    '.kaattttooooyooottttaak.',
    '.kaatttttooooootttttaak.',
    '.kaattttttoooottttttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_elecres: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaatttcttcttcttctttaak.',
    '.kaattccccccccccccttaak.',
    '.kaatttcttcttcttctttaak.',
    '.kaatttcttcttcttctttaak.',
    '.kaattccccccccccccttaak.',
    '.kaatttcttcttcttctttaak.',
    '.kaatttcttcttcttctttaak.',
    '.kaattccccccccccccttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_battery: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaattttttttttttttttaak.',
    '.kaatttlllllllllttttaak.',
    '.kaatttlgggggttlttttaak.',
    '.kaatttlgggggttlltttaak.',
    '.kaatttlgggggttlltttaak.',
    '.kaatttlgggggttlttttaak.',
    '.kaatttlllllllllttttaak.',
    '.kaattttttttttttttttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_coolant: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaatttttttcctttctttaak.',
    '.kaatttttcccccccttttaak.',
    '.kaatttttcttttcwttttaak.',
    '.kaattttccttttccttttaak.',
    '.kaattttccttttccttttaak.',
    '.kaatttttcttttctttttaak.',
    '.kaatttttcccccctttttaak.',
    '.kaatttttttcctttttttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_target: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnRRnnnnnnnaak.',
    '.kaattttttRRRRttttttaak.',
    '.kaatttttRtRRtRtttttaak.',
    '.kaattttRttttttRttttaak.',
    '.kaattRRRttwwttRRRttaak.',
    '.kaattRRRttwwttRRRttaak.',
    '.kaattttRttttttRttttaak.',
    '.kaatttttRtRRtRtttttaak.',
    '.kaattttttRRRRttttttaak.',
    '.kaatttttttRRtttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_servo: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaallaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaattttttllllttttttaak.',
    '.kaatttttlllllltttttaak.',
    '.kaattttlllttlllttttaak.',
    '.kaattltllttttlltlttaak.',
    '.kaattltllttttlltlttaak.',
    '.kaattttlllttlllttttaak.',
    '.kaatttttlllllllllltaak.',
    '.kaattttttlllldddddtaak.',
    '.kaattttttttttdddddtaak.',
    '.kaaaaaaaaallaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_bounty: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaattttttyyyyttttttaak.',
    '.kaatttttywyyoytttttaak.',
    '.kaattttyooyyooyttttaak.',
    '.kaattttyooyyooyttttaak.',
    '.kaattttyooyyooyttttaak.',
    '.kaattttyooyyooyttttaak.',
    '.kaatttttyoyyoytttttaak.',
    '.kaattttttyyyyttttttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_salvage: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaattttlllllllltgttaak.',
    '.kaattttllllllllttgtaak.',
    '.kaattttlltlltlltgttaak.',
    '.kaattttlltlltllttttaak.',
    '.kaattttlltlltllttttaak.',
    '.kaattttlltlltllttttaak.',
    '.kaattttlltlwtllttttaak.',
    '.kaattttlwttttlwttttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_governor: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaattttttttttttttttaak.',
    '.kaattttttlllottttttaak.',
    '.kaattttlllllooottttaak.',
    '.kaatttllllttowootttaak.',
    '.kaatttllltttwoootttaak.',
    '.kaatttlltttwttootttaak.',
    '.kaattlllttwtttooottaak.',
    '.kaattttttttttttttttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_thermal: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnllnnnnnnnaak.',
    '.kaatttttttlltllttttaak.',
    '.kaatttttttRRtttttttaak.',
    '.kaatttttttRRtllttttaak.',
    '.kaatttttttRRtttttttaak.',
    '.kaatttttttRRtllttttaak.',
    '.kaatttttttRRtttttttaak.',
    '.kaattttttRwRRttttttaak.',
    '.kaattttttRRRRttttttaak.',
    '.kaatttttttRRtttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_capacitor: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnlnnnlnnnlnnnnaak.',
    '.kaatttltttltttlttttaak.',
    '.kaattwwwtwwwtwwwtttaak.',
    '.kaattccctccctccctttaak.',
    '.kaattccctccctccctttaak.',
    '.kaattccctccctccctttaak.',
    '.kaattccctccctccctttaak.',
    '.kaattccctccctccctttaak.',
    '.kaattccctccctccctttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_heatsink: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannllnoonoonllnnnaak.',
    '.kaattlltootootlltttaak.',
    '.kaattlltootootlltttaak.',
    '.kaattlltootootlltttaak.',
    '.kaattlltootootlltttaak.',
    '.kaattlltootootlltttaak.',
    '.kaattlltootootlltttaak.',
    '.kaattllllllllllllttaak.',
    '.kaattllllllllllllttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_generator: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaatttttsssssstttttaak.',
    '.kaattttssnnynssttttaak.',
    '.kaattttsnnynnnsttttaak.',
    '.kaattttsnyyyynsttttaak.',
    '.kaattttsnnnynnsttttaak.',
    '.kaattttsnnynnnsttttaak.',
    '.kaattttssynnnssttttaak.',
    '.kaatttttsssssstttttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_fluxcell: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaatthhhhhhhhhhhhttaak.',
    '.kaattaaaaaaaaaaaattaak.',
    '.kaattaaccccooooaattaak.',
    '.kaattaacwccoyooaattaak.',
    '.kaattaaccccooooaattaak.',
    '.kaattaaccccooooaattaak.',
    '.kaattaaaaaaaaaaaattaak.',
    '.kaattaaaaaaaaaaaattaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_twinloop: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaattttttttttttttttaak.',
    '.kaatttccccttooootttaak.',
    '.kaattccttcwoottowttaak.',
    '.kaattcttttcottttottaak.',
    '.kaattcttttcottttottaak.',
    '.kaattccttccoottoottaak.',
    '.kaatttccccttooootttaak.',
    '.kaattttttttttttttttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_fusion: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnoonnnnnnnaak.',
    '.kaattttttottottttttaak.',
    '.kaattttttottottttttaak.',
    '.kaatttyyttttttyytttaak.',
    '.kaatyyttttwwttttyytaak.',
    '.kaatyyttttwwttttyytaak.',
    '.kaatttyyttttttyytttaak.',
    '.kaattttttottottttttaak.',
    '.kaattttttottottttttaak.',
    '.kaatttttttootttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_amp: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaatttttttRRtttttttaak.',
    '.kaattttttRwwRttttttaak.',
    '.kaatttttRRRRRRtttttaak.',
    '.kaattttRRRRRRRRttttaak.',
    '.kaatttRRRRRRRRRRtttaak.',
    '.kaattttttRRRRttttttaak.',
    '.kaattttttRRRRttttttaak.',
    '.kaattttttRRRRttttttaak.',
    '.kaattttttRRRRttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_repair: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaattttttggggttttttaak.',
    '.kaattttttgwwgttttttaak.',
    '.kaatttggggwwggggtttaak.',
    '.kaatttgwwwwwwwwgtttaak.',
    '.kaatttgwwwwwwwwgtttaak.',
    '.kaatttggggwwggggtttaak.',
    '.kaattttttgwwgttttttaak.',
    '.kaattttttggggttttttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_exchanger: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaattttttttttotttttaak.',
    '.kaatttooooooooootttaak.',
    '.kaatttttttttyotttttaak.',
    '.kaattttttttytttttttaak.',
    '.kaatttttttyyyytttttaak.',
    '.kaatttttctttyttttttaak.',
    '.kaatttcccccycccctttaak.',
    '.kaatttttctyttttttttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_laststand: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaattttttwwwwttttttaak.',
    '.kaatttttwwwwwwtttttaak.',
    '.kaattttwkkwwkkwttttaak.',
    '.kaattttwkkwwkkwttttaak.',
    '.kaattttwwwwwwwwttttaak.',
    '.kaatttttwwkkwwtttttaak.',
    '.kaatttttwwwwwwtttttaak.',
    '.kaatttttwwwwwwtttttaak.',
    '.kaatttttwkwkwktttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_range: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnnnnnnnnnnnaak.',
    '.kaattttttttttttttttaak.',
    '.kaattlttdttttttttttaak.',
    '.kaattlttdttttttytttaak.',
    '.kaattlwwdwwwwwwyyttaak.',
    '.kaattllldllllllyyttaak.',
    '.kaattlttdttttttytttaak.',
    '.kaattlttdttttttttttaak.',
    '.kaattttttttttttttttaak.',
    '.kaattttttttttttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_overclock: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaayaaaaaaaaaak.',
    '.kaannnnnnnllnnnnnnnaak.',
    '.kaatttttllyllltttttaak.',
    '.kaattttllnynnllttttaak.',
    '.kaattttlnnynnnlttttaak.',
    '.kaattyllnnwyyylltttaak.',
    '.kaatttllnnnnnnllyttaak.',
    '.kaattttlnnnnnnlttttaak.',
    '.kaattttllnnnnllttttaak.',
    '.kaatttttlllllltttttaak.',
    '.kaatttttttlltttttttaak.',
    '.kaaaaaaaaayaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
  md_singularity: [
    '...klkklkklkklkklkklk...',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '.khhhhhhhhhhhhhhhhhhhhk.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kaannnnnnppppnnnnnnaak.',
    '.kaatttttppppppwttttaak.',
    '.kaattttppRRppppttttaak.',
    '.kaatttppRpkkpppptttaak.',
    '.kaatttppRkkkkppptttaak.',
    '.kaatttpppkkkkRpptttaak.',
    '.kaatttppppkkpRpptttaak.',
    '.kaattttppppRRppttttaak.',
    '.kaatttwtpppppptttttaak.',
    '.kaattttttppppttttttaak.',
    '.kaaaaaaaaaaaaaaaaaaaak.',
    '.kbbbbbbbbbbbbbbbbbbbbk.',
    '..kkdkkdkkdkkdkkdkkdkk..',
    '...klkklkklkklkklkklk...',
  ],
};

// ---------- Painting ----------

function paint(grid, colors) {
  const h = grid.length;
  const w = Math.max(...grid.map((r) => r.length));
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  const g = c.getContext('2d');
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < grid[y].length; x++) {
      const col = colors[grid[y][x]] || PAL[grid[y][x]];
      if (!col) continue;
      g.fillStyle = col;
      g.fillRect(x, y, 1, 1);
    }
  }
  return c;
}

/** Plating modules show as plating on a steel torso, like the mech wears it. */
const PLATING = new Set(['md_plating', 'md_heavyplate', 'md_composite', 'md_insulated', 'md_aegis', 'md_titanplate', 'md_voidcore']);

const canvasCache = new Map();
const urlCache = new Map();

/** Rebuild every cached sprite/icon canvas on next use (they can go blank after a long background). */
export function resetSpriteCaches() {
  canvasCache.clear();
  clearMechSpriteCache();
}

/** Canvas with a part's icon (for drawing into other canvases). */
export function partCanvas(id, colorOverride) {
  const key = `p:${id}:${colorOverride || ''}`;
  if (!canvasCache.has(key)) {
    const p = getPart(id);
    const base = colorOverride || p?.color || rarityColor(p?.rarity);
    // Frames, legs and plating use the same sprites the mech wears in battle
    if (p?.type === 'frame') canvasCache.set(key, torsoCanvas(id, null, base, shade(base, -0.45)));
    else if (p?.type === 'legs') canvasCache.set(key, legsCanvas(id, base, shade(base, -0.45)));
    else if (PLATING.has(id)) canvasCache.set(key, torsoCanvas('fr_brawler', id, '#566c86', '#333c57')); // plating on a steel torso
    else {
      const cols = { a: base, h: shade(base, 0.45), b: shade(base, -0.45) };
      const hi = HI_GRIDS[id] || HI_GRIDS[p?.icon];
      const c = paint(hi || TYPE_GRIDS[p?.type] || TYPE_GRIDS.module, cols);
      if (hi) c.px = 2;
      canvasCache.set(key, c);
    }
  }
  return canvasCache.get(key);
}

/** A part icon's size in old (12-wide) pixels: hi-res canvases count half. */
export const iconSize = (c) => ({ w: c.width / (c.px || 1), h: c.height / (c.px || 1) });

/** Data URL of a part's icon, for <img>. */
export function partIcon(id, colorOverride) {
  const key = `p:${id}:${colorOverride || ''}`;
  if (!urlCache.has(key)) urlCache.set(key, partCanvas(id, colorOverride).toDataURL());
  return urlCache.get(key);
}

/** Canvas for a UI icon; `tint` recolours a pod (a/h/b letters). */
export function iconCanvas(name, tint = '#94b0c2') {
  const key = `u:${name}:${tint}`;
  if (!canvasCache.has(key)) {
    canvasCache.set(key, paint(UI_GRIDS[name] || UI_GRIDS.star, { a: tint, h: shade(tint, 0.45), b: shade(tint, -0.45) }));
  }
  return canvasCache.get(key);
}

export function uiIcon(name, tint) {
  const key = `u:${name}:${tint || ''}`;
  if (!urlCache.has(key)) urlCache.set(key, iconCanvas(name, tint).toDataURL());
  return urlCache.get(key);
}

/** Inline <img> for a UI icon, sized by CSS class `pxi`. */
export const ico = (name, tint) => `<img class="pxi" src="${uiIcon(name, tint)}" alt="">`;
